version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - ipstack
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  ipstack1:
    image: ajishantony2020/ipstack1:latest
    container_name: ipstack1
    restart: always
    networks:
      - ipstack
    environment:
      CACHING_SERVER: "${CACHING_SERVER}"
      IPSTACK_KEY: "${IPSTACK_KEY}"

  ipstack2:
    image: ajishantony2020/ipstack1:latest
    container_name: ipstack2
    restart: always
    networks:
      - ipstack
    environment:
      CACHING_SERVER: "${CACHING_SERVER}"
      IPSTACK_KEY: "${IPSTACK_KEY}"

  ipstack3:
    image: ajishantony2020/ipstack1:latest
    container_name: ipstack3
    restart: always
    networks:
      - ipstack
    environment:
      CACHING_SERVER: "${CACHING_SERVER}"
      IPSTACK_KEY: "${IPSTACK_KEY}"
networks:
  ipstack:
